server:
  port: 9000

AUTH_SERVICE_URL: http://localhost:9030
AUTO_SERVICE_URL: http://localhost:9031
COMPARADOR_SERVICE_URL: http://localhost:9032
FAVORITO_SERVICE_URL: http://localhost:9033

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL}
          predicates:
            - Path=/api/auth/**
        # Auto (protegido)
        - id: auto-service
          uri: ${AUTO_SERVICE_URL}
          predicates:
            - Path=/api/autos/**
          filters:
            - StripPrefix=0

        # Comparador (protegido)
        - id: comparador-service
          uri: ${COMPARADOR_SERVICE_URL}
          predicates:
            - Path=/api/comparar/**
          filters:
            - StripPrefix=0

        # Favoritos (protegido)
        - id: favorito-service
          uri: ${FAVORITO_SERVICE_URL}
          predicates:
            - Path=/api/favoritos/**
          filters:
            - StripPrefix=0